-- MySQL Script generated by MySQL Workbench
-- Wed Apr  2 21:50:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema floricultura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema floricultura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `floricultura` DEFAULT CHARACTER SET utf8 ;
USE `floricultura` ;

-- -----------------------------------------------------
-- Table `floricultura`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floricultura`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` ENUM("RS", "SC", "PR") NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `floricultura`.`notas_fiscais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floricultura`.`notas_fiscais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_compra` DATETIME NOT NULL,
  `valor_total` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '								';


-- -----------------------------------------------------
-- Table `floricultura`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floricultura`.`clientes` (
  `numero_rg` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `numero_telefone` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`numero_rg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `floricultura`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floricultura`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco` FLOAT UNSIGNED ZEROFILL NOT NULL,
  `quantidade_estoque` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `floricultura`.`flores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floricultura`.`flores` (
  `cor` VARCHAR(50) NOT NULL,
  `estacao_ano` VARCHAR(45) NULL,
  `aroma` VARCHAR(45) NULL,
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_produto`),
  CONSTRAINT `chave_estra`
    FOREIGN KEY (`id_produto`)
    REFERENCES `floricultura`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '																																																																			';


-- -----------------------------------------------------
-- Table `floricultura`.`plantas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floricultura`.`plantas` (
  `frutifera` TINYINT NULL,
  `descricao_fruta` VARCHAR(45) NULL,
  `produtos_id` INT NOT NULL,
  PRIMARY KEY (`produtos_id`),
  CONSTRAINT `fk_plantas_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `floricultura`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `floricultura`.`vasos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floricultura`.`vasos` (
  `material` VARCHAR(50) NULL,
  `formato` VARCHAR(45) NULL,
  `tamanho` VARCHAR(45) NULL,
  `produtos_id` INT NOT NULL,
  PRIMARY KEY (`produtos_id`),
  CONSTRAINT `fk_vasos_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `floricultura`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `floricultura`.`notas_fiscais_e_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `floricultura`.`notas_fiscais_e_produtos` (
  `produtos` INT NULL,
  `notas_fiscais` INT NULL,
  INDEX `produtos_idx` (`produtos` ASC, `notas_fiscais` ASC) VISIBLE,
  INDEX `notas_idx` (`notas_fiscais` ASC) VISIBLE,
  CONSTRAINT `produtos`
    FOREIGN KEY (`produtos` , `notas_fiscais`)
    REFERENCES `floricultura`.`produtos` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `notas`
    FOREIGN KEY (`notas_fiscais`)
    REFERENCES `floricultura`.`notas_fiscais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
